package vista;

import javax.swing.UIManager;

public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        etiMINDEL = new javax.swing.JLabel();
        etiUserName = new javax.swing.JLabel();
        etiContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MINDEL ™");
        setMinimumSize(new java.awt.Dimension(550, 370));
        setPreferredSize(new java.awt.Dimension(550, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));

        etiMINDEL.setBackground(new java.awt.Color(255, 255, 255));
        etiMINDEL.setText("MINDEL");
        etiMINDEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiMINDEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        etiUserName.setBackground(new java.awt.Color(255, 255, 255));
        etiUserName.setText("UserName: ");
        etiUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        etiContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        etiContrasenia.setText("Password: ");
        etiContrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, -1));
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        lblFondo.setMaximumSize(new java.awt.Dimension(353, 206));
        lblFondo.setMinimumSize(new java.awt.Dimension(353, 206));
        lblFondo.setPreferredSize(new java.awt.Dimension(353, 206));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEntrar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JLabel etiContrasenia;
    public javax.swing.JLabel etiMINDEL;
    public javax.swing.JLabel etiUserName;
    public javax.swing.JLabel lblFondo;
    public javax.swing.JPasswordField txtContrasenia;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
