/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class menuEmpleado extends javax.swing.JDialog {

    /**
     * Creates new form menu
     */
    public menuEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRevisarMenu = new javax.swing.JButton();
        btnSalirMenu = new javax.swing.JButton();
        btnOfertaMenu = new javax.swing.JButton();
        btnOfertaAMenu = new javax.swing.JButton();
        btnPedidoMenu = new javax.swing.JButton();
        btnProveedorMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(366, 223));
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        btnRevisarMenu.setText("Revisar Compras");
        getContentPane().add(btnRevisarMenu);
        getContentPane().add(btnSalirMenu);

        btnOfertaMenu.setText("Crear oferta");
        getContentPane().add(btnOfertaMenu);

        btnOfertaAMenu.setText("Aplicar oferta");
        getContentPane().add(btnOfertaAMenu);

        btnPedidoMenu.setText("Pedir un Envio");
        getContentPane().add(btnPedidoMenu);

        btnProveedorMenu.setText("Contratar Proveedor");
        getContentPane().add(btnProveedorMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuEmpleado dialog = new menuEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnOfertaAMenu;
    public javax.swing.JButton btnOfertaMenu;
    public javax.swing.JButton btnPedidoMenu;
    public javax.swing.JButton btnProveedorMenu;
    public javax.swing.JButton btnRevisarMenu;
    public javax.swing.JButton btnSalirMenu;
    // End of variables declaration//GEN-END:variables
}
